name: Tests

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        dim1: ["d1.1", "d1.2"]
        dim2: ["d2.1", "d2.2"]

    steps:
    - uses: actions/checkout@v2
      id: s1
    #- run: echo ${{ matrix.dim1 }}-${{ matrix.dim2 }} 
    #  name: Use ${{ matrix.dim1 }}-${{ matrix.dim2 }}  
    - uses: LouisBrunner/checks-action@v1.6.0
      if: always()
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Test XYZ ${{ matrix.dim1 }}-${{ matrix.dim2 }}
        sha: 3cc3831d3e46307e85aa84445d0ece3f23bad2d4
        conclusion: ${{ job.status }}
        output: |
          {"summary":"${{ matrix.dim1 }}-${{ matrix.dim2 }}"}

